// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repo struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	Owner     string             `json:"owner"`
	Tags      []string           `json:"tags"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
