// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (name, url, owner, tags, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, url, owner, tags, active, created_at, updated_at
`

type CreateRepoParams struct {
	Name   string   `json:"name"`
	Url    string   `json:"url"`
	Owner  string   `json:"owner"`
	Tags   []string `json:"tags"`
	Active bool     `json:"active"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.Name,
		arg.Url,
		arg.Owner,
		arg.Tags,
		arg.Active,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Owner,
		&i.Tags,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos
WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const getRepo = `-- name: GetRepo :one
SELECT id, name, url, owner, tags, active, created_at, updated_at FROM repos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRepo(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Owner,
		&i.Tags,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByName = `-- name: GetRepoByName :one
SELECT id, name, url, owner, tags, active, created_at, updated_at FROM repos
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRepoByName(ctx context.Context, name string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByName, name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Owner,
		&i.Tags,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRepos = `-- name: ListActiveRepos :many
SELECT id, name, url, owner, tags, active, created_at, updated_at FROM repos
WHERE active = TRUE
ORDER BY name
`

func (q *Queries) ListActiveRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listActiveRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Owner,
			&i.Tags,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT id, name, url, owner, tags, active, created_at, updated_at FROM repos
ORDER BY name
`

func (q *Queries) ListRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Owner,
			&i.Tags,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepo = `-- name: UpdateRepo :one
UPDATE repos
SET
    url = coalesce($1, url),
    owner = coalesce($2, owner),
    tags = coalesce($3, tags),
    active = coalesce($4, active),
    updated_at = now()
WHERE id = $5
RETURNING id, name, url, owner, tags, active, created_at, updated_at
`

type UpdateRepoParams struct {
	Url    *string  `json:"url"`
	Owner  *string  `json:"owner"`
	Tags   []string `json:"tags"`
	Active *bool    `json:"active"`
	ID     int64    `json:"id"`
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepo,
		arg.Url,
		arg.Owner,
		arg.Tags,
		arg.Active,
		arg.ID,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Owner,
		&i.Tags,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
